# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 35e30e285ca113bbee60dd335dd4e75fedc38f61a50554d5016e93f1559e33e4cad4492f23b83dab4bc348dfe13ae9bbb52f63b5d457f0563fcce74347724ee2

test:
  secret_key_base: f0a5978abbe715a20da6638dd3fd8986a2f0c2f7981d6c5f79de2e4fb04336719d0e34f6f48b8327eb86e776a5cf7ea43bce9ce6d4979cf90f5858d0a16d37de

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
